import os
import gspread
from google.oauth2.service_account import Credentials
from notion_client import Client as NotionClient

SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]

def _get_gspread_client():
    sa_path = os.environ["GOOGLE_SERVICE_ACCOUNT_JSON"]
    creds = Credentials.from_service_account_file(sa_path, scopes=SCOPES)
    return gspread.authorize(creds)

def sheets_append_row(tab_name: str, row: list):
    sheet_id = os.environ["SHEET_ID"]
    gc = _get_gspread_client()
    sh = gc.open_by_key(sheet_id)
    ws = sh.worksheet(tab_name)
    ws.append_row(row, value_input_option="USER_ENTERED")

def notion_client():
    return NotionClient(auth=os.environ["NOTION_TOKEN"])

def notion_upsert_month_page(month: str, parent_page_id: str, title_suffix: str = "Plan & Close"):
    notion = notion_client()
    # For simplicity: always create a new page. You can later "search and update" by month property.
    page = notion.pages.create(
        parent={"page_id": parent_page_id},
        properties={
            "title": [{"type": "text", "text": {"content": f"{month} — {title_suffix}"}}]
        },
        children=[
            {"object": "block", "type": "heading_2", "heading_2": {"rich_text": [{"type":"text","text":{"content":"Summary"}}]}},
            {"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type":"text","text":{"content":"(Auto-generated by PocketPilot)"}}]}},
        ],
    )
    return {"page_id": page["id"], "page_url": page.get("url")}
